project_id = "owtylihsslimxdiovxia"

[functions.populate-materiais-from-pdf]
verify_jwt = true

[functions.generate-flashcards]
verify_jwt = true

[functions.generate-questions]
verify_jwt = true

[functions.parse-pdf]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.study-chat]
verify_jwt = true

[functions.import-traffic-signs]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false