project_id = "owtylihsslimxdiovxia"

[functions.populate-materiais-from-pdf]
verify_jwt = false

[functions.generate-flashcards]
verify_jwt = false

[functions.generate-questions]
verify_jwt = false

[functions.parse-pdf]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true