project_id = "owtylihsslimxdiovxia"

[functions.populate-materiais-from-pdf]
verify_jwt = true

[functions.generate-flashcards]
verify_jwt = true

[functions.generate-questions]
verify_jwt = true

[functions.parse-pdf]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.study-chat]
verify_jwt = true

[functions.import-traffic-signs]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.create-abacate-pix]
verify_jwt = true

[functions.verify-abacate-pix]
verify_jwt = true
[functions.validate-coupon]
enabled = true
verify_jwt = true
import_map = "./functions/validate-coupon/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/validate-coupon/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/validate-coupon/*.html" ]
